/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedParametresRouteImport } from './routes/_authenticated/parametres'
import { Route as AuthenticatedHistoriqueRouteImport } from './routes/_authenticated/historique'
import { Route as AuthenticatedFicheRouteImport } from './routes/_authenticated/fiche'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedFicheBilanRouteImport } from './routes/_authenticated/fiche.bilan'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedParametresRoute = AuthenticatedParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoriqueRoute = AuthenticatedHistoriqueRouteImport.update({
  id: '/historique',
  path: '/historique',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFicheRoute = AuthenticatedFicheRouteImport.update({
  id: '/fiche',
  path: '/fiche',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFicheBilanRoute = AuthenticatedFicheBilanRouteImport.update({
  id: '/bilan',
  path: '/bilan',
  getParentRoute: () => AuthenticatedFicheRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fiche': typeof AuthenticatedFicheRouteWithChildren
  '/historique': typeof AuthenticatedHistoriqueRoute
  '/parametres': typeof AuthenticatedParametresRoute
  '/fiche/bilan': typeof AuthenticatedFicheBilanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fiche': typeof AuthenticatedFicheRouteWithChildren
  '/historique': typeof AuthenticatedHistoriqueRoute
  '/parametres': typeof AuthenticatedParametresRoute
  '/fiche/bilan': typeof AuthenticatedFicheBilanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/fiche': typeof AuthenticatedFicheRouteWithChildren
  '/_authenticated/historique': typeof AuthenticatedHistoriqueRoute
  '/_authenticated/parametres': typeof AuthenticatedParametresRoute
  '/_authenticated/fiche/bilan': typeof AuthenticatedFicheBilanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/fiche'
    | '/historique'
    | '/parametres'
    | '/fiche/bilan'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/fiche'
    | '/historique'
    | '/parametres'
    | '/fiche/bilan'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/fiche'
    | '/_authenticated/historique'
    | '/_authenticated/parametres'
    | '/_authenticated/fiche/bilan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/parametres': {
      id: '/_authenticated/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof AuthenticatedParametresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historique': {
      id: '/_authenticated/historique'
      path: '/historique'
      fullPath: '/historique'
      preLoaderRoute: typeof AuthenticatedHistoriqueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fiche': {
      id: '/_authenticated/fiche'
      path: '/fiche'
      fullPath: '/fiche'
      preLoaderRoute: typeof AuthenticatedFicheRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fiche/bilan': {
      id: '/_authenticated/fiche/bilan'
      path: '/bilan'
      fullPath: '/fiche/bilan'
      preLoaderRoute: typeof AuthenticatedFicheBilanRouteImport
      parentRoute: typeof AuthenticatedFicheRoute
    }
  }
}

interface AuthenticatedFicheRouteChildren {
  AuthenticatedFicheBilanRoute: typeof AuthenticatedFicheBilanRoute
}

const AuthenticatedFicheRouteChildren: AuthenticatedFicheRouteChildren = {
  AuthenticatedFicheBilanRoute: AuthenticatedFicheBilanRoute,
}

const AuthenticatedFicheRouteWithChildren =
  AuthenticatedFicheRoute._addFileChildren(AuthenticatedFicheRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFicheRoute: typeof AuthenticatedFicheRouteWithChildren
  AuthenticatedHistoriqueRoute: typeof AuthenticatedHistoriqueRoute
  AuthenticatedParametresRoute: typeof AuthenticatedParametresRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFicheRoute: AuthenticatedFicheRouteWithChildren,
  AuthenticatedHistoriqueRoute: AuthenticatedHistoriqueRoute,
  AuthenticatedParametresRoute: AuthenticatedParametresRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
