/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedParametresRouteImport } from './routes/_authenticated/parametres'
import { Route as AuthenticatedHistoriqueRouteImport } from './routes/_authenticated/historique'
import { Route as AuthenticatedFicheRouteImport } from './routes/_authenticated/fiche'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBilanRouteImport } from './routes/_authenticated/bilan'
import { Route as AuthenticatedAdminValidationRouteImport } from './routes/_authenticated/admin.validation'
import { Route as AuthenticatedAdminStatistiquesRouteImport } from './routes/_authenticated/admin.statistiques'
import { Route as AuthenticatedAdminGestionRouteImport } from './routes/_authenticated/admin.gestion'
import { Route as AuthenticatedAdminEmployesRouteImport } from './routes/_authenticated/admin.employes'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin.dashboard'
import { Route as AuthenticatedAdminEmployesIdRouteImport } from './routes/_authenticated/admin.employes.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedParametresRoute = AuthenticatedParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoriqueRoute = AuthenticatedHistoriqueRouteImport.update({
  id: '/historique',
  path: '/historique',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFicheRoute = AuthenticatedFicheRouteImport.update({
  id: '/fiche',
  path: '/fiche',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBilanRoute = AuthenticatedBilanRouteImport.update({
  id: '/bilan',
  path: '/bilan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminValidationRoute =
  AuthenticatedAdminValidationRouteImport.update({
    id: '/admin/validation',
    path: '/admin/validation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminStatistiquesRoute =
  AuthenticatedAdminStatistiquesRouteImport.update({
    id: '/admin/statistiques',
    path: '/admin/statistiques',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminGestionRoute =
  AuthenticatedAdminGestionRouteImport.update({
    id: '/admin/gestion',
    path: '/admin/gestion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminEmployesRoute =
  AuthenticatedAdminEmployesRouteImport.update({
    id: '/admin/employes',
    path: '/admin/employes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/admin/dashboard',
    path: '/admin/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminEmployesIdRoute =
  AuthenticatedAdminEmployesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminEmployesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/bilan': typeof AuthenticatedBilanRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fiche': typeof AuthenticatedFicheRoute
  '/historique': typeof AuthenticatedHistoriqueRoute
  '/parametres': typeof AuthenticatedParametresRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/employes': typeof AuthenticatedAdminEmployesRouteWithChildren
  '/admin/gestion': typeof AuthenticatedAdminGestionRoute
  '/admin/statistiques': typeof AuthenticatedAdminStatistiquesRoute
  '/admin/validation': typeof AuthenticatedAdminValidationRoute
  '/admin/employes/$id': typeof AuthenticatedAdminEmployesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/bilan': typeof AuthenticatedBilanRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fiche': typeof AuthenticatedFicheRoute
  '/historique': typeof AuthenticatedHistoriqueRoute
  '/parametres': typeof AuthenticatedParametresRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/employes': typeof AuthenticatedAdminEmployesRouteWithChildren
  '/admin/gestion': typeof AuthenticatedAdminGestionRoute
  '/admin/statistiques': typeof AuthenticatedAdminStatistiquesRoute
  '/admin/validation': typeof AuthenticatedAdminValidationRoute
  '/admin/employes/$id': typeof AuthenticatedAdminEmployesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/_authenticated/bilan': typeof AuthenticatedBilanRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/fiche': typeof AuthenticatedFicheRoute
  '/_authenticated/historique': typeof AuthenticatedHistoriqueRoute
  '/_authenticated/parametres': typeof AuthenticatedParametresRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/employes': typeof AuthenticatedAdminEmployesRouteWithChildren
  '/_authenticated/admin/gestion': typeof AuthenticatedAdminGestionRoute
  '/_authenticated/admin/statistiques': typeof AuthenticatedAdminStatistiquesRoute
  '/_authenticated/admin/validation': typeof AuthenticatedAdminValidationRoute
  '/_authenticated/admin/employes/$id': typeof AuthenticatedAdminEmployesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/bilan'
    | '/dashboard'
    | '/fiche'
    | '/historique'
    | '/parametres'
    | '/admin/dashboard'
    | '/admin/employes'
    | '/admin/gestion'
    | '/admin/statistiques'
    | '/admin/validation'
    | '/admin/employes/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/bilan'
    | '/dashboard'
    | '/fiche'
    | '/historique'
    | '/parametres'
    | '/admin/dashboard'
    | '/admin/employes'
    | '/admin/gestion'
    | '/admin/statistiques'
    | '/admin/validation'
    | '/admin/employes/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/auth'
    | '/_authenticated/bilan'
    | '/_authenticated/dashboard'
    | '/_authenticated/fiche'
    | '/_authenticated/historique'
    | '/_authenticated/parametres'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/employes'
    | '/_authenticated/admin/gestion'
    | '/_authenticated/admin/statistiques'
    | '/_authenticated/admin/validation'
    | '/_authenticated/admin/employes/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/parametres': {
      id: '/_authenticated/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof AuthenticatedParametresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historique': {
      id: '/_authenticated/historique'
      path: '/historique'
      fullPath: '/historique'
      preLoaderRoute: typeof AuthenticatedHistoriqueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fiche': {
      id: '/_authenticated/fiche'
      path: '/fiche'
      fullPath: '/fiche'
      preLoaderRoute: typeof AuthenticatedFicheRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bilan': {
      id: '/_authenticated/bilan'
      path: '/bilan'
      fullPath: '/bilan'
      preLoaderRoute: typeof AuthenticatedBilanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/validation': {
      id: '/_authenticated/admin/validation'
      path: '/admin/validation'
      fullPath: '/admin/validation'
      preLoaderRoute: typeof AuthenticatedAdminValidationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/statistiques': {
      id: '/_authenticated/admin/statistiques'
      path: '/admin/statistiques'
      fullPath: '/admin/statistiques'
      preLoaderRoute: typeof AuthenticatedAdminStatistiquesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/gestion': {
      id: '/_authenticated/admin/gestion'
      path: '/admin/gestion'
      fullPath: '/admin/gestion'
      preLoaderRoute: typeof AuthenticatedAdminGestionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/employes': {
      id: '/_authenticated/admin/employes'
      path: '/admin/employes'
      fullPath: '/admin/employes'
      preLoaderRoute: typeof AuthenticatedAdminEmployesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/employes/$id': {
      id: '/_authenticated/admin/employes/$id'
      path: '/$id'
      fullPath: '/admin/employes/$id'
      preLoaderRoute: typeof AuthenticatedAdminEmployesIdRouteImport
      parentRoute: typeof AuthenticatedAdminEmployesRoute
    }
  }
}

interface AuthenticatedAdminEmployesRouteChildren {
  AuthenticatedAdminEmployesIdRoute: typeof AuthenticatedAdminEmployesIdRoute
}

const AuthenticatedAdminEmployesRouteChildren: AuthenticatedAdminEmployesRouteChildren =
  {
    AuthenticatedAdminEmployesIdRoute: AuthenticatedAdminEmployesIdRoute,
  }

const AuthenticatedAdminEmployesRouteWithChildren =
  AuthenticatedAdminEmployesRoute._addFileChildren(
    AuthenticatedAdminEmployesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBilanRoute: typeof AuthenticatedBilanRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFicheRoute: typeof AuthenticatedFicheRoute
  AuthenticatedHistoriqueRoute: typeof AuthenticatedHistoriqueRoute
  AuthenticatedParametresRoute: typeof AuthenticatedParametresRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminEmployesRoute: typeof AuthenticatedAdminEmployesRouteWithChildren
  AuthenticatedAdminGestionRoute: typeof AuthenticatedAdminGestionRoute
  AuthenticatedAdminStatistiquesRoute: typeof AuthenticatedAdminStatistiquesRoute
  AuthenticatedAdminValidationRoute: typeof AuthenticatedAdminValidationRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBilanRoute: AuthenticatedBilanRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFicheRoute: AuthenticatedFicheRoute,
  AuthenticatedHistoriqueRoute: AuthenticatedHistoriqueRoute,
  AuthenticatedParametresRoute: AuthenticatedParametresRoute,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminEmployesRoute: AuthenticatedAdminEmployesRouteWithChildren,
  AuthenticatedAdminGestionRoute: AuthenticatedAdminGestionRoute,
  AuthenticatedAdminStatistiquesRoute: AuthenticatedAdminStatistiquesRoute,
  AuthenticatedAdminValidationRoute: AuthenticatedAdminValidationRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
